# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Dylan0513/Github/Gravitate

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Dylan0513/Github/Gravitate

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Dylan0513/Github/Gravitate/CMakeFiles /Users/Dylan0513/Github/Gravitate/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Dylan0513/Github/Gravitate/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Gravitate

# Build rule for target.
Gravitate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gravitate
.PHONY : Gravitate

# fast build rule for target.
Gravitate/fast:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/build
.PHONY : Gravitate/fast

bin/Gravitate.o: bin/Gravitate.cpp.o
.PHONY : bin/Gravitate.o

# target to build an object file
bin/Gravitate.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/bin/Gravitate.cpp.o
.PHONY : bin/Gravitate.cpp.o

bin/Gravitate.i: bin/Gravitate.cpp.i
.PHONY : bin/Gravitate.i

# target to preprocess a source file
bin/Gravitate.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/bin/Gravitate.cpp.i
.PHONY : bin/Gravitate.cpp.i

bin/Gravitate.s: bin/Gravitate.cpp.s
.PHONY : bin/Gravitate.s

# target to generate assembly for a file
bin/Gravitate.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/bin/Gravitate.cpp.s
.PHONY : bin/Gravitate.cpp.s

src/Actor.o: src/Actor.cpp.o
.PHONY : src/Actor.o

# target to build an object file
src/Actor.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/Actor.cpp.o
.PHONY : src/Actor.cpp.o

src/Actor.i: src/Actor.cpp.i
.PHONY : src/Actor.i

# target to preprocess a source file
src/Actor.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/Actor.cpp.i
.PHONY : src/Actor.cpp.i

src/Actor.s: src/Actor.cpp.s
.PHONY : src/Actor.s

# target to generate assembly for a file
src/Actor.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/Actor.cpp.s
.PHONY : src/Actor.cpp.s

src/ActorComponentInterface.o: src/ActorComponentInterface.cpp.o
.PHONY : src/ActorComponentInterface.o

# target to build an object file
src/ActorComponentInterface.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/ActorComponentInterface.cpp.o
.PHONY : src/ActorComponentInterface.cpp.o

src/ActorComponentInterface.i: src/ActorComponentInterface.cpp.i
.PHONY : src/ActorComponentInterface.i

# target to preprocess a source file
src/ActorComponentInterface.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/ActorComponentInterface.cpp.i
.PHONY : src/ActorComponentInterface.cpp.i

src/ActorComponentInterface.s: src/ActorComponentInterface.cpp.s
.PHONY : src/ActorComponentInterface.s

# target to generate assembly for a file
src/ActorComponentInterface.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/ActorComponentInterface.cpp.s
.PHONY : src/ActorComponentInterface.cpp.s

src/ActorFactory.o: src/ActorFactory.cpp.o
.PHONY : src/ActorFactory.o

# target to build an object file
src/ActorFactory.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/ActorFactory.cpp.o
.PHONY : src/ActorFactory.cpp.o

src/ActorFactory.i: src/ActorFactory.cpp.i
.PHONY : src/ActorFactory.i

# target to preprocess a source file
src/ActorFactory.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/ActorFactory.cpp.i
.PHONY : src/ActorFactory.cpp.i

src/ActorFactory.s: src/ActorFactory.cpp.s
.PHONY : src/ActorFactory.s

# target to generate assembly for a file
src/ActorFactory.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/ActorFactory.cpp.s
.PHONY : src/ActorFactory.cpp.s

src/DisplayManager.o: src/DisplayManager.cpp.o
.PHONY : src/DisplayManager.o

# target to build an object file
src/DisplayManager.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/DisplayManager.cpp.o
.PHONY : src/DisplayManager.cpp.o

src/DisplayManager.i: src/DisplayManager.cpp.i
.PHONY : src/DisplayManager.i

# target to preprocess a source file
src/DisplayManager.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/DisplayManager.cpp.i
.PHONY : src/DisplayManager.cpp.i

src/DisplayManager.s: src/DisplayManager.cpp.s
.PHONY : src/DisplayManager.s

# target to generate assembly for a file
src/DisplayManager.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/DisplayManager.cpp.s
.PHONY : src/DisplayManager.cpp.s

src/EventManager.o: src/EventManager.cpp.o
.PHONY : src/EventManager.o

# target to build an object file
src/EventManager.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/EventManager.cpp.o
.PHONY : src/EventManager.cpp.o

src/EventManager.i: src/EventManager.cpp.i
.PHONY : src/EventManager.i

# target to preprocess a source file
src/EventManager.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/EventManager.cpp.i
.PHONY : src/EventManager.cpp.i

src/EventManager.s: src/EventManager.cpp.s
.PHONY : src/EventManager.s

# target to generate assembly for a file
src/EventManager.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/EventManager.cpp.s
.PHONY : src/EventManager.cpp.s

src/GameApplication.o: src/GameApplication.cpp.o
.PHONY : src/GameApplication.o

# target to build an object file
src/GameApplication.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameApplication.cpp.o
.PHONY : src/GameApplication.cpp.o

src/GameApplication.i: src/GameApplication.cpp.i
.PHONY : src/GameApplication.i

# target to preprocess a source file
src/GameApplication.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameApplication.cpp.i
.PHONY : src/GameApplication.cpp.i

src/GameApplication.s: src/GameApplication.cpp.s
.PHONY : src/GameApplication.s

# target to generate assembly for a file
src/GameApplication.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameApplication.cpp.s
.PHONY : src/GameApplication.cpp.s

src/GameLogicManager.o: src/GameLogicManager.cpp.o
.PHONY : src/GameLogicManager.o

# target to build an object file
src/GameLogicManager.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameLogicManager.cpp.o
.PHONY : src/GameLogicManager.cpp.o

src/GameLogicManager.i: src/GameLogicManager.cpp.i
.PHONY : src/GameLogicManager.i

# target to preprocess a source file
src/GameLogicManager.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameLogicManager.cpp.i
.PHONY : src/GameLogicManager.cpp.i

src/GameLogicManager.s: src/GameLogicManager.cpp.s
.PHONY : src/GameLogicManager.s

# target to generate assembly for a file
src/GameLogicManager.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameLogicManager.cpp.s
.PHONY : src/GameLogicManager.cpp.s

src/GameOwner.o: src/GameOwner.cpp.o
.PHONY : src/GameOwner.o

# target to build an object file
src/GameOwner.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameOwner.cpp.o
.PHONY : src/GameOwner.cpp.o

src/GameOwner.i: src/GameOwner.cpp.i
.PHONY : src/GameOwner.i

# target to preprocess a source file
src/GameOwner.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameOwner.cpp.i
.PHONY : src/GameOwner.cpp.i

src/GameOwner.s: src/GameOwner.cpp.s
.PHONY : src/GameOwner.s

# target to generate assembly for a file
src/GameOwner.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameOwner.cpp.s
.PHONY : src/GameOwner.cpp.s

src/GamePlayer.o: src/GamePlayer.cpp.o
.PHONY : src/GamePlayer.o

# target to build an object file
src/GamePlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GamePlayer.cpp.o
.PHONY : src/GamePlayer.cpp.o

src/GamePlayer.i: src/GamePlayer.cpp.i
.PHONY : src/GamePlayer.i

# target to preprocess a source file
src/GamePlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GamePlayer.cpp.i
.PHONY : src/GamePlayer.cpp.i

src/GamePlayer.s: src/GamePlayer.cpp.s
.PHONY : src/GamePlayer.s

# target to generate assembly for a file
src/GamePlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GamePlayer.cpp.s
.PHONY : src/GamePlayer.cpp.s

src/GameStateComponent.o: src/GameStateComponent.cpp.o
.PHONY : src/GameStateComponent.o

# target to build an object file
src/GameStateComponent.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameStateComponent.cpp.o
.PHONY : src/GameStateComponent.cpp.o

src/GameStateComponent.i: src/GameStateComponent.cpp.i
.PHONY : src/GameStateComponent.i

# target to preprocess a source file
src/GameStateComponent.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameStateComponent.cpp.i
.PHONY : src/GameStateComponent.cpp.i

src/GameStateComponent.s: src/GameStateComponent.cpp.s
.PHONY : src/GameStateComponent.s

# target to generate assembly for a file
src/GameStateComponent.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/GameStateComponent.cpp.s
.PHONY : src/GameStateComponent.cpp.s

src/HumanPlayer.o: src/HumanPlayer.cpp.o
.PHONY : src/HumanPlayer.o

# target to build an object file
src/HumanPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/HumanPlayer.cpp.o
.PHONY : src/HumanPlayer.cpp.o

src/HumanPlayer.i: src/HumanPlayer.cpp.i
.PHONY : src/HumanPlayer.i

# target to preprocess a source file
src/HumanPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/HumanPlayer.cpp.i
.PHONY : src/HumanPlayer.cpp.i

src/HumanPlayer.s: src/HumanPlayer.cpp.s
.PHONY : src/HumanPlayer.s

# target to generate assembly for a file
src/HumanPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/HumanPlayer.cpp.s
.PHONY : src/HumanPlayer.cpp.s

src/PhysicalComponent.o: src/PhysicalComponent.cpp.o
.PHONY : src/PhysicalComponent.o

# target to build an object file
src/PhysicalComponent.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/PhysicalComponent.cpp.o
.PHONY : src/PhysicalComponent.cpp.o

src/PhysicalComponent.i: src/PhysicalComponent.cpp.i
.PHONY : src/PhysicalComponent.i

# target to preprocess a source file
src/PhysicalComponent.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/PhysicalComponent.cpp.i
.PHONY : src/PhysicalComponent.cpp.i

src/PhysicalComponent.s: src/PhysicalComponent.cpp.s
.PHONY : src/PhysicalComponent.s

# target to generate assembly for a file
src/PhysicalComponent.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/PhysicalComponent.cpp.s
.PHONY : src/PhysicalComponent.cpp.s

src/SelectionToolBarComponent.o: src/SelectionToolBarComponent.cpp.o
.PHONY : src/SelectionToolBarComponent.o

# target to build an object file
src/SelectionToolBarComponent.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/SelectionToolBarComponent.cpp.o
.PHONY : src/SelectionToolBarComponent.cpp.o

src/SelectionToolBarComponent.i: src/SelectionToolBarComponent.cpp.i
.PHONY : src/SelectionToolBarComponent.i

# target to preprocess a source file
src/SelectionToolBarComponent.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/SelectionToolBarComponent.cpp.i
.PHONY : src/SelectionToolBarComponent.cpp.i

src/SelectionToolBarComponent.s: src/SelectionToolBarComponent.cpp.s
.PHONY : src/SelectionToolBarComponent.s

# target to generate assembly for a file
src/SelectionToolBarComponent.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/SelectionToolBarComponent.cpp.s
.PHONY : src/SelectionToolBarComponent.cpp.s

src/Shape.o: src/Shape.cpp.o
.PHONY : src/Shape.o

# target to build an object file
src/Shape.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/Shape.cpp.o
.PHONY : src/Shape.cpp.o

src/Shape.i: src/Shape.cpp.i
.PHONY : src/Shape.i

# target to preprocess a source file
src/Shape.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/Shape.cpp.i
.PHONY : src/Shape.cpp.i

src/Shape.s: src/Shape.cpp.s
.PHONY : src/Shape.s

# target to generate assembly for a file
src/Shape.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/Shape.cpp.s
.PHONY : src/Shape.cpp.s

src/VectorMathExtension.o: src/VectorMathExtension.cpp.o
.PHONY : src/VectorMathExtension.o

# target to build an object file
src/VectorMathExtension.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/VectorMathExtension.cpp.o
.PHONY : src/VectorMathExtension.cpp.o

src/VectorMathExtension.i: src/VectorMathExtension.cpp.i
.PHONY : src/VectorMathExtension.i

# target to preprocess a source file
src/VectorMathExtension.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/VectorMathExtension.cpp.i
.PHONY : src/VectorMathExtension.cpp.i

src/VectorMathExtension.s: src/VectorMathExtension.cpp.s
.PHONY : src/VectorMathExtension.s

# target to generate assembly for a file
src/VectorMathExtension.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/VectorMathExtension.cpp.s
.PHONY : src/VectorMathExtension.cpp.s

src/VisualComponent.o: src/VisualComponent.cpp.o
.PHONY : src/VisualComponent.o

# target to build an object file
src/VisualComponent.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/VisualComponent.cpp.o
.PHONY : src/VisualComponent.cpp.o

src/VisualComponent.i: src/VisualComponent.cpp.i
.PHONY : src/VisualComponent.i

# target to preprocess a source file
src/VisualComponent.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/VisualComponent.cpp.i
.PHONY : src/VisualComponent.cpp.i

src/VisualComponent.s: src/VisualComponent.cpp.s
.PHONY : src/VisualComponent.s

# target to generate assembly for a file
src/VisualComponent.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/VisualComponent.cpp.s
.PHONY : src/VisualComponent.cpp.s

src/tinyxml2.o: src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.o

# target to build an object file
src/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.cpp.o

src/tinyxml2.i: src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.i

# target to preprocess a source file
src/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.cpp.i

src/tinyxml2.s: src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.s

# target to generate assembly for a file
src/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/Gravitate.dir/build.make CMakeFiles/Gravitate.dir/src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Gravitate"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bin/Gravitate.o"
	@echo "... bin/Gravitate.i"
	@echo "... bin/Gravitate.s"
	@echo "... src/Actor.o"
	@echo "... src/Actor.i"
	@echo "... src/Actor.s"
	@echo "... src/ActorComponentInterface.o"
	@echo "... src/ActorComponentInterface.i"
	@echo "... src/ActorComponentInterface.s"
	@echo "... src/ActorFactory.o"
	@echo "... src/ActorFactory.i"
	@echo "... src/ActorFactory.s"
	@echo "... src/DisplayManager.o"
	@echo "... src/DisplayManager.i"
	@echo "... src/DisplayManager.s"
	@echo "... src/EventManager.o"
	@echo "... src/EventManager.i"
	@echo "... src/EventManager.s"
	@echo "... src/GameApplication.o"
	@echo "... src/GameApplication.i"
	@echo "... src/GameApplication.s"
	@echo "... src/GameLogicManager.o"
	@echo "... src/GameLogicManager.i"
	@echo "... src/GameLogicManager.s"
	@echo "... src/GameOwner.o"
	@echo "... src/GameOwner.i"
	@echo "... src/GameOwner.s"
	@echo "... src/GamePlayer.o"
	@echo "... src/GamePlayer.i"
	@echo "... src/GamePlayer.s"
	@echo "... src/GameStateComponent.o"
	@echo "... src/GameStateComponent.i"
	@echo "... src/GameStateComponent.s"
	@echo "... src/HumanPlayer.o"
	@echo "... src/HumanPlayer.i"
	@echo "... src/HumanPlayer.s"
	@echo "... src/PhysicalComponent.o"
	@echo "... src/PhysicalComponent.i"
	@echo "... src/PhysicalComponent.s"
	@echo "... src/SelectionToolBarComponent.o"
	@echo "... src/SelectionToolBarComponent.i"
	@echo "... src/SelectionToolBarComponent.s"
	@echo "... src/Shape.o"
	@echo "... src/Shape.i"
	@echo "... src/Shape.s"
	@echo "... src/VectorMathExtension.o"
	@echo "... src/VectorMathExtension.i"
	@echo "... src/VectorMathExtension.s"
	@echo "... src/VisualComponent.o"
	@echo "... src/VisualComponent.i"
	@echo "... src/VisualComponent.s"
	@echo "... src/tinyxml2.o"
	@echo "... src/tinyxml2.i"
	@echo "... src/tinyxml2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

